[project]
name = 'Decentralized-Manufacturing-Production-Planning'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.capacity-planning]
path = 'contracts/capacity-planning.clar'
clarity_version = 2
epoch = 2.5

[contracts.demand-forecasting]
path = 'contracts/demand-forecasting.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
